name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎉 New Features'
    labels:
      - 'feat'
  - title: '🚀 performance Enhancements'
    labels:
      - 'pref'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: 'Other Changes'
    labels:
      - 'style'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # What's Changed

  $CHANGES
no-changes-template: |
  快下载体验~